### ISSUE TITLE
Please add maven / jcenter coordinates to README.md

### ISSUE THREAD

**Issue by bastman** [dmcg/minutest#34]
Its hard to figure out, where to get the library from.

Could you please provide a hint within the README.md ?

Thanks a lot :)

**Comment by robstoll** [comment]
see https://github.com/dmcg/minutest/blob/master/docs/installation.md, does this help? Feel free to propose improvements

**Comment by bastman** [comment]
Yes this helps. Thanks a lot.

But the the link to JCenter in installation.md is broken ;)

"You can find the latest binaries and source in a Maven-compatible format on JCenter"

click on "JCenter" -> https://bintray.com/dmcg/oneeyedmen-mvn/minutest -> 404

**Comment by dmcg** [comment]
Good catch thanks.
