### ISSUE TITLE
Test name printing on console running gradle is cryptic

### ISSUE THREAD

**Issue by arturbosch** [dmcg/minutest#6]
Hey, thanks for the library.

When running `gradle test` the name of the tests is not the same as specified in the testcases.
It is just `tests()[number]`

Please see the output:
```
io.gitlab.arturbosch.afk.uast.visit.TraversingSpec > allows to traverse back to UFile PASSED
io.gitlab.arturbosch.afk.uast.visit.UastRegistrarSpec > Given: registered UFile visit event PASSED
io.gitlab.arturbosch.afk.uast.visit.UastRegistrarSpec > When: two different lang UFiles are visited PASSED
io.gitlab.arturbosch.afk.uast.visit.UastRegistrarSpec > Then: the event counter must be two PASSED
io.gitlab.arturbosch.afk.uast.visit.UastVisitorSpec > prints names PASSED
io.gitlab.arturbosch.afk.uast.visit.TraversingTest > tests()[1] PASSED
io.gitlab.arturbosch.afk.uast.visit.TraversingTest > tests()[2] PASSED
io.gitlab.arturbosch.afk.uast.KotlinParsingSpec > tests()[1] PASSED
io.gitlab.arturbosch.afk.uast.KotlinParsingSpec > tests()[2] PASSED
```

The first four tests are written using spek2 and the last four minutest.

Gradle is 4.10.2, Kotlin 1.3, Junit 5.3.1, Junit-Platform 1.3.1, minutest 0.20.0, strikt 0.16.4

greetings.

**Comment by npryce** [comment]
This appears to be a bug in Gradle: https://github.com/gradle/gradle/issues/5975

**Comment by dmcg** [comment]
I think that Spek has its own runner, which might explain how it doesn't suffer.

**Comment by dmcg** [comment]
I'm going to leave this open for reference although it isn't clear what we can do about it, short of fixing Gradle. Which might be an option. I mean, how hard can it be?
